import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));
const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "동작 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const phase7Tools: ToolDefinition[] = [
  {
    slug: "ai-token-calculator",
    categoryId: "dev",
    title: "AI 토큰 계산기",
    shortTitle: "토큰 계산",
    description: "입력 텍스트의 대략적인 토큰 수를 계산합니다.",
    metaDescription: "AI 토큰 계산기: 문자 수 기반 대략 토큰 추정.",
    relatedSlugs: ["prompt-length", "model-cost-estimator", "text-chunk-splitter", "char-count"],
    seoTitle: "AI 토큰 계산기 | 텍스트 토큰 추정",
    ogDescription: "문자 수 기반으로 LLM 토큰 수를 대략 계산합니다.",
    keywords: ["토큰 계산기", "LLM 토큰", "프롬프트 토큰"],
    isNew: true,
    featured: true,
    faq: faq([{ q: "정확한 토큰 수와 같은가요?", a: "아니요. 모델별 토크나이저가 달라 참고용입니다." }]),
    toolSections: sec("텍스트를 넣으면 추정 토큰 수를 표시합니다.", "문자 수 기반 근사치를 사용합니다.", "긴 문서 사전 점검", "정밀 계산은 모델 공식 토크나이저를 사용하세요."),
  },
  {
    slug: "prompt-length",
    categoryId: "dev",
    title: "프롬프트 길이 계산기",
    shortTitle: "프롬프트 길이",
    description: "프롬프트 추정 토큰과 컨텍스트 사용률을 계산합니다.",
    metaDescription: "프롬프트 길이 계산: 컨텍스트 한도 대비 사용률.",
    relatedSlugs: ["ai-token-calculator", "model-cost-estimator", "text-chunk-splitter", "json-schema-template"],
    seoTitle: "프롬프트 길이 계산기",
    ogDescription: "컨텍스트 길이 대비 프롬프트 사용률을 빠르게 점검합니다.",
    keywords: ["프롬프트 길이", "컨텍스트 윈도우", "LLM 한도"],
    isNew: true,
    featured: true,
    faq: faq([{ q: "사용률 100% 이하면 안전한가요?", a: "출력 토큰·시스템 프롬프트 여유를 남기는 것이 좋습니다." }]),
    toolSections: sec("컨텍스트 길이와 프롬프트를 입력합니다.", "추정 토큰/컨텍스트 비율로 계산합니다.", "8k 컨텍스트 기준 점검", "출력 토큰 여유를 항상 고려하세요."),
  },
  {
    slug: "model-cost-estimator",
    categoryId: "dev",
    title: "모델 비용 추정기",
    shortTitle: "비용 추정",
    description: "입출력 토큰과 단가로 API 비용을 추정합니다.",
    metaDescription: "모델 비용 추정: 입력/출력 토큰과 1M 단가로 계산.",
    relatedSlugs: ["ai-token-calculator", "prompt-length", "text-chunk-splitter", "exchange-rate"],
    seoTitle: "모델 비용 추정기 | LLM API 단가 계산",
    ogDescription: "입력/출력 토큰 비용을 분리해 계산합니다.",
    keywords: ["LLM 비용", "토큰 단가", "API 비용 계산"],
    isNew: true,
    featured: true,
    faq: faq([{ q: "환율 반영은 되나요?", a: "기본은 USD입니다. 필요하면 환율 계산기와 함께 사용하세요." }]),
    toolSections: sec("토큰 수와 모델 단가를 입력합니다.", "비용=(토큰/1,000,000)×단가", "입력 12만, 출력 3만", "최소 청구 단위·세금은 별도일 수 있습니다."),
  },
  {
    slug: "text-chunk-splitter",
    categoryId: "dev",
    title: "텍스트 청크 분할기",
    shortTitle: "청크 분할",
    description: "긴 텍스트를 청크/오버랩 기준으로 분할합니다.",
    metaDescription: "텍스트 청크 분할기: chunk size·overlap 설정.",
    relatedSlugs: ["ai-token-calculator", "prompt-length", "model-cost-estimator", "line-dedupe"],
    seoTitle: "텍스트 청크 분할기",
    ogDescription: "긴 문서를 청크 단위로 나눠 전처리를 돕습니다.",
    keywords: ["텍스트 청크", "RAG 전처리", "chunk overlap"],
    isNew: true,
    featured: true,
    faq: faq([{ q: "문장 단위로 자동 분할하나요?", a: "현재는 문자 수 기준 분할입니다." }]),
    toolSections: sec("원문, 청크 길이, 오버랩을 입력합니다.", "문자 길이 기준으로 순차 분할합니다.", "500/50 설정", "임베딩 품질은 데이터 특성에 따라 다를 수 있습니다."),
  },
  {
    slug: "json-schema-template",
    categoryId: "dev",
    title: "JSON Schema 템플릿 생성기",
    shortTitle: "Schema 템플릿",
    description: "샘플 JSON에서 기본 스키마 템플릿을 생성합니다.",
    metaDescription: "JSON 샘플로 기본 JSON Schema 템플릿 생성.",
    relatedSlugs: ["json-format", "csv-json", "prompt-length", "model-cost-estimator"],
    seoTitle: "JSON Schema 템플릿 생성기",
    ogDescription: "샘플 JSON을 바탕으로 기본 스키마 구조를 만듭니다.",
    keywords: ["JSON Schema", "스키마 생성", "템플릿"],
    isNew: true,
    featured: true,
    faq: faq([{ q: "완전한 스키마인가요?", a: "기본 타입 추론 템플릿이며 세부 제약은 추가해야 합니다." }]),
    toolSections: sec("샘플 JSON을 입력합니다.", "값 타입을 보고 기본 스키마를 생성합니다.", "객체/배열 샘플", "배열 내부 타입 혼합 등 복잡 케이스는 수동 조정이 필요합니다."),
  },
];

