import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));

const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "동작 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const phase2Tools: ToolDefinition[] = [
  {
    slug: "markdown-preview",
    categoryId: "dev",
    title: "Markdown 미리보기",
    shortTitle: "Markdown",
    seoTitle: "Markdown 미리보기 | 편집·복사",
    ogDescription: "Markdown을 입력하면 오른쪽에 미리보기. 표·목록·코드 블록 지원. 브라우저만.",
    description: "Markdown을 쓰면 바로 미리보기로 확인하고 HTML이나 원문을 복사합니다.",
    introText: "문서 초안·리드미·이슈 본문을 빠르게 검토할 때 씁니다.",
    metaDescription:
      "Markdown 미리보기: GFM 표·체크리스트·코드. 좌우 분할·모바일 세로 스택. 로컬만.",
    keywords: ["Markdown", "미리보기", "GFM", "리드미", "md"],
    bodyText: "렌더링은 일반적인 GFM 규칙에 가깝게 두었습니다. 플랫폼마다 미세한 차이가 있을 수 있습니다.",
    relatedIntro: "JSON·CSV·슬러그·해시 작업과 같은 편집 흐름에 넣기 좋습니다.",
    relatedSlugs: ["json-format", "csv-json", "slugify", "hash-generator"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "왼쪽에 Markdown을 입력하면 오른쪽에 미리보기가 갱신됩니다. 모바일에서는 위·아래로 쌓입니다.",
      "remark-gfm 기준으로 표·취소선·작업 목록 등을 지원합니다.",
      "# 제목과 리스트·코드 블록으로 시험해 보세요.",
      "원문에 스크립트를 넣어도 이 페이지는 안전한 컴포넌트 렌더만 사용합니다.",
    ),
    faq: faq([
      { q: "HTML을 넣을 수 있나요?", a: "기본 설정에서는 원시 HTML을 렌더하지 않습니다." },
      { q: "미리보기만 복사되나요?", a: "Markdown 원문 복사 버튼을 따로 두었습니다." },
      { q: "이미지는?", a: "URL 이미지는 네트워크가 허용될 때만 보입니다." },
      { q: "VS Code와 같나요?", a: "완전히 같지는 않습니다. 최종은 배포 환경에서 확인하세요." },
      { q: "서버에 저장되나요?", a: "아니요." },
      { q: "PDF로 내보내기는?", a: "브라우저 인쇄를 쓰세요." },
    ]),
  },
  {
    slug: "csv-json",
    categoryId: "text",
    title: "CSV ↔ JSON 변환",
    shortTitle: "CSV·JSON",
    seoTitle: "CSV JSON 변환기 | 붙여넣기",
    ogDescription: "CSV를 JSON 배열로, JSON을 CSV로 바꿉니다. 오류 메시지로 맞춤.",
    description: "표 형식 CSV와 JSON 배열을 서로 변환합니다.",
    introText: "스프레드시트에서 복사한 데이터를 API 형식으로 바꿀 때 씁니다.",
    metaDescription: "CSV JSON 변환: 헤더 행·배열 객체. 검증·복사. 브라우저만.",
    keywords: ["CSV JSON", "CSV 변환", "JSON CSV", "엑셀 JSON"],
    bodyText: "따옴표·쉼표가 섞인 셀은 파서 규칙에 따라 달라질 수 있습니다.",
    relatedIntro: "JSON 포맷터·줄 정리·Markdown과 이어서 쓰기 좋습니다.",
    relatedSlugs: ["json-format", "markdown-preview", "whitespace", "line-dedupe"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "모드를 고른 뒤 텍스트를 붙여 넣습니다. 오류가 나면 줄 번호·메시지를 확인하세요.",
      "CSV는 첫 줄을 헤더로 두는 형태를 권장합니다. JSON은 객체 배열을 기대합니다.",
      "name,age 형 CSV와 [{\"name\":\"a\"}] 형 JSON으로 시험해 보세요.",
      "대용량은 브라우저가 느려질 수 있습니다.",
    ),
    faq: faq([
      { q: "한글이 깨져요.", a: "UTF-8로 저장·복사했는지 확인하세요." },
      { q: "JSON이 배열이 아니에요.", a: "단일 객체는 배열로 감싸거나 모드를 바꿔 보세요." },
      { q: "구분자가 쉼표가 아니에요.", a: "이 도구는 쉼표 기준입니다." },
      { q: "빈 줄은?", a: "무시하거나 오류가 날 수 있습니다." },
      { q: "서버 전송?", a: "하지 않습니다." },
      { q: "Excel에서?", a: "CSV로 저장 후 붙여 넣는 편이 안전합니다." },
    ]),
  },
  {
    slug: "exchange-rate",
    categoryId: "calculator",
    title: "환율 계산기",
    shortTitle: "환율",
    seoTitle: "환율 계산기 | 최신 기준 참고",
    ogDescription: "기준 통화·상대 통화·금액을 넣으면 환산합니다. ECB 기준 Frankfurter API.",
    description: "선택한 통화 쌍과 금액으로 환율을 환산합니다.",
    introText: "여행·쇼핑·송금 전에 대략 금액을 맞출 때 씁니다. 실거래·신고용이 아닙니다.",
    metaDescription: "환율 계산: KRW USD EUR 등. 공개 API 기준, 날짜 표시. 모바일.",
    keywords: ["환율 계산기", "달러 환율", "원화 달러", "환율 환산"],
    bodyText: "Frankfurter(ECB 시세 기반) 공개 API를 사용합니다. 장애 시 재시도하거나 금융사 화면을 확인하세요.",
    relatedIntro: "퍼센트·팁·여행 단위 변환과 같이 보면 편합니다.",
    relatedSlugs: ["percent", "tip-calculator", "world-clock", "split-bill"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "기준 통화·상대 통화·금액을 고른 뒤 최신 환율을 불러옵니다. 네트워크가 필요합니다.",
      "1 기준 통화당 상대 통화 비율로 곱합니다.",
      "100 USD를 KRW로 바꾸는 식으로 시험해 보세요.",
      "실제 거래 스프레드·수수료는 반영하지 않습니다.",
    ),
    faq: faq([
      { q: "실시간인가요?", a: "API가 제공하는 최신 영업일 기준입니다." },
      { q: "모든 통화가 있나요?", a: "API가 지원하는 통화만 선택할 수 있습니다." },
      { q: "오류가 나요.", a: "네트워크·API 제한일 수 있습니다. 잠시 뒤 다시 시도하세요." },
      { q: "송금할 때 그대로 써도 되나요?", a: "참고용입니다. 은행·카드사 환율을 확인하세요." },
      { q: "암호화폐는?", a: "지원하지 않습니다." },
      { q: "역산도 되나요?", a: "기준과 상대를 바꿔 같은 금액으로 확인할 수 있습니다." },
    ]),
  },
  {
    slug: "todo-checklist",
    categoryId: "utility",
    title: "체크리스트 (할 일)",
    shortTitle: "할 일",
    seoTitle: "체크리스트 | 로컬 저장",
    ogDescription: "할 일을 추가·체크·삭제합니다. localStorage에만 저장됩니다.",
    description: "브라우저에만 저장되는 간단한 할 일 목록입니다.",
    introText: "짧은 메모·장보기 목록처럼 가볍게 쓸 때 적합합니다. 다른 기기와 동기화되지 않습니다.",
    metaDescription: "할 일 리스트: 체크·삭제·로컬 저장. 로그인 없음.",
    keywords: ["체크리스트", "할 일", "todo", "로컬 저장"],
    bodyText: "브라우저 저장소를 지우면 목록이 사라집니다. 중요한 일정은 별도 백업을 쓰세요.",
    relatedIntro: "타이머·날짜·메모형 텍스트 도구와 같이 쓰기 좋습니다.",
    relatedSlugs: ["timer-stopwatch", "date", "markdown-preview", "random-picker"],
    isNew: true,
    toolSections: sec(
      "항목을 추가하고 완료하면 체크합니다. 삭제는 항목별로 할 수 있습니다.",
      "같은 브라우저·같은 기기에서만 유지됩니다.",
      "쇼핑·준비물처럼 짧은 목록을 적어 보세요.",
      "민감한 개인정보는 적지 마세요.",
    ),
    faq: faq([
      { q: "다른 폰에서도 보나요?", a: "아니요. 서버에 올리지 않습니다." },
      { q: "순서를 바꿀 수 있나요?", a: "현재 버전은 위·아래 추가·삭제 중심입니다." },
      { q: "내보내기는?", a: "복사는 항목을 직접 선택해 쓰세요." },
      { q: "데이터가 사라졌어요.", a: "사이트 데이터 삭제·시크릿 모드 종료 시 없어질 수 있습니다." },
      { q: "동기화 앱과 같나요?", a: "아닙니다. 가벼운 메모용입니다." },
      { q: "알림은?", a: "없습니다. 타이머 도구를 함께 쓰세요." },
    ]),
  },
  {
    slug: "timer-stopwatch",
    categoryId: "utility",
    title: "타이머 · 스톱워치 · 뽀모도로",
    shortTitle: "타이머",
    seoTitle: "타이머 스톱워치 뽀모도로 | 브라우저",
    ogDescription: "카운트다운·스톱워치·25분 뽀모도로. 탭을 닫으면 멈출 수 있습니다.",
    description: "타이머·스톱워치·뽀모도로(25분)를 한 페이지에서 씁니다.",
    introText: "집중 시간을 나누거나 측정할 때 씁니다. 소리 알림은 브라우저 설정에 따릅니다.",
    metaDescription: "타이머·스톱워치·뽀모도로: 시작·일시정지·초기화. 무료, 로그인 없음.",
    keywords: ["타이머", "스톱워치", "뽀모도로", "집중 타이머"],
    bodyText: "백그라운드 제한으로 탭이 비활성일 때 정확도가 떨어질 수 있습니다.",
    relatedIntro: "할 일 목록·날짜 계산기와 같이 쓰면 작업 흐름을 잡기 좋습니다.",
    relatedSlugs: ["todo-checklist", "date", "world-clock", "sleep-cycle"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "상단에서 탭을 고릅니다. 타이머는 목표 시간을 정하고 시작합니다.",
      "스톱워치는 경과 시간을 측정합니다. 뽀모도로는 25분 카운트다운입니다.",
      "5분 휴식이 필요하면 타이머에 300초를 넣어 보세요.",
      "법적·의료적 시간 측정에는 적합하지 않을 수 있습니다.",
    ),
    faq: faq([
      { q: "알림 소리는?", a: "선택 시 짧은 비프음을 재생할 수 있습니다. 브라우저가 막을 수 있습니다." },
      { q: "백그라운드에서도 가나요?", a: "브라우저·기기에 따라 멈추거나 느려질 수 있습니다." },
      { q: "뽀모도로 시간을 바꿀 수 있나요?", a: "타이머 탭에서 초 단위로 직접 넣을 수 있습니다." },
      { q: "기록이 저장되나요?", a: "저장하지 않습니다." },
      { q: "전체화면은?", a: "브라우저 기능을 쓰세요." },
      { q: "운동 인터벌용으로?", a: "대략 참고용입니다." },
    ]),
  },
];
