import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));

const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "계산·동작 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const phase1Tools: ToolDefinition[] = [
  {
    slug: "qr-code-generator",
    categoryId: "utility",
    title: "QR 코드 생성기",
    shortTitle: "QR 코드",
    seoTitle: "QR 코드 생성기 | URL·텍스트·다운로드",
    ogDescription: "텍스트나 URL을 QR 코드로 만듭니다. 크기 조절·PNG 저장. 브라우저에서만 생성합니다.",
    description: "문자열이나 링크를 QR 코드로 바꾸고 PNG로 저장합니다.",
    introText: "현장 공유·메뉴·Wi‑Fi 안내처럼 빠르게 코드가 필요할 때 씁니다. 입력값은 서버로 보내지 않습니다.",
    metaDescription:
      "QR 코드 생성: 텍스트·URL 입력, 크기 선택, 미리보기·PNG 다운로드. 무료, 로그인 없음, 모바일 지원.",
    keywords: ["QR 코드", "QR 생성", "QR 다운로드", "URL QR", "무료 QR"],
    bodyText: "인쇄·표시 크기에 맞게 여백을 조정해 보세요. 오류 복원 레벨은 라이브러리 기본값을 따릅니다.",
    relatedIntro: "링크 인코딩·짧은 식별자가 필요하면 아래 도구로 이어가 보세요.",
    relatedSlugs: ["url-encode", "uuid-generator", "hash-generator", "base64"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "입력란에 넣을 내용을 쓰고, 크기를 고른 뒤 미리보기를 확인합니다. 저장이 필요하면 PNG로 받습니다.",
      "QR은 문자열을 흑백 패턴으로 인코딩합니다. 길이가 길수록 모듈이 촘촘해집니다.",
      "https:// 로 시작하는 URL이나 짧은 문장을 넣어 볼 수 있습니다.",
      "결제·본인 확인 등 보안 목적의 진위 검증은 전용 시스템을 사용하세요.",
    ),
    faq: faq([
      { q: "최대 몇 자까지 되나요?", a: "버전·인코딩에 따라 달라집니다. 너무 길면 패턴이 커지니 짧은 URL을 쓰는 편이 좋습니다." },
      { q: "스캔이 안 돼요.", a: "대비·크기·손떨림을 확인하고, 내용이 너무 길지 않은지 봐 주세요." },
      { q: "로고를 넣을 수 있나요?", a: "이 도구는 기본 패턴만 만듭니다." },
      { q: "Wi‑Fi용 QR은?", a: "표준 문자열 형식(WIFI:T:...)을 입력 칸에 그대로 넣을 수 있습니다." },
      { q: "데이터가 서버에 가나요?", a: "브라우저에서만 그립니다." },
      { q: "색을 바꿀 수 있나요?", a: "현재는 흑백 기본값입니다." },
    ]),
  },
  {
    slug: "hash-generator",
    categoryId: "dev",
    title: "해시 생성기 (MD5·SHA-1·SHA-256)",
    shortTitle: "해시",
    seoTitle: "해시 생성기 | MD5 SHA-1 SHA-256",
    ogDescription: "텍스트를 UTF-8로 해시합니다. MD5·SHA-1·SHA-256 결과를 한 화면에서 복사합니다.",
    description: "입력 문자열의 MD5, SHA-1, SHA-256 해시를 계산합니다.",
    introText: "파일 무결성 확인·개발 테스트용으로 쓸 수 있습니다. 비밀번호 저장용 해시로는 적합하지 않습니다.",
    metaDescription:
      "텍스트 해시: MD5, SHA-1, SHA-256. 브라우저 Web Crypto·로컬 계산, 복사 가능. 로그인 불필요.",
    keywords: ["해시", "MD5", "SHA-256", "SHA-1", "체크섬"],
    bodyText: "MD5·SHA-1은 레거시 호환용으로만 참고하세요. 보안이 필요한 서명·암호는 최신 표준과 전문 도구를 쓰세요.",
    relatedIntro: "인코딩·UUID·Base64 작업과 같은 흐름에서 쓰기 좋습니다.",
    relatedSlugs: ["uuid-generator", "base64", "binary-converter", "json-format"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "텍스트를 입력하면 세 가지 해시가 갱신됩니다. 결과 줄을 각각 복사할 수 있습니다.",
      "문자열은 UTF-8 바이트로 변환한 뒤 해시합니다. 빈 문자열도 정의된 값이 있습니다.",
      "hello 같은 짧은 단어로 결과 길이·형식을 확인해 볼 수 있습니다.",
      "비밀번호를 여기에 넣어도 ‘안전하게 저장’되지는 않습니다. 테스트용만 사용하세요.",
    ),
    faq: faq([
      { q: "비밀번호 해싱에 쓰면 되나요?", a: "아니요. 전용 KDF·소금·서버 정책이 필요합니다." },
      { q: "파일 해시는?", a: "이 페이지는 텍스트만 다룹니다. 파일은 별도 도구를 쓰세요." },
      { q: "MD5가 짧게 나와요.", a: "MD5는 128비트(16바이트)라 16진수 32자입니다." },
      { q: "SHA 결과가 달라요.", a: "인코딩·줄바꿈·공백이 다르면 해시도 달라집니다." },
      { q: "한글도 되나요?", a: "UTF-8 기준으로 처리합니다." },
      { q: "서버에 전송되나요?", a: "브라우저에서만 계산합니다." },
    ]),
  },
  {
    slug: "inch-cm",
    categoryId: "convert",
    title: "인치 ↔ cm 변환",
    shortTitle: "인치·cm",
    seoTitle: "인치 cm 변환기 | 양방향 실시간",
    ogDescription: "국제 인치(2.54cm) 기준으로 인치와 센티미터를 바꿉니다.",
    description: "인치와 cm를 서로 변환합니다. 1인치 = 2.54cm 고정입니다.",
    introText: "모니터·인쇄·수공예 치수를 맞출 때 쓰는 참고용입니다.",
    metaDescription: "인치 cm 환산: 2.54 기준 양방향. 실시간 계산, 모바일.",
    keywords: ["인치 cm", "inch cm", "센티미터 인치", "단위 변환"],
    bodyText: "영국식 등 다른 ‘인치’ 정의는 사용하지 않습니다.",
    relatedIntro: "다른 길이·무게·온도 변환과 함께 쓰면 편합니다.",
    relatedSlugs: ["kg-lb", "celsius-fahrenheit", "data-unit-converter", "area"],
    isNew: true,
    toolSections: sec(
      "방향을 고른 뒤 한쪽에 숫자를 넣으면 반대 단위가 맞춰집니다.",
      "1 in = 2.54 cm 정확히 사용합니다.",
      "10인치는 약 25.4cm입니다.",
      "측정 도구 오차는 반영하지 않습니다.",
    ),
    faq: faq([
      { q: "왜 2.54인가요?", a: "국제적으로 통용되는 인치 정의입니다." },
      { q: "소수는?", a: "표시 자릿수는 반올림될 수 있습니다." },
      { q: "피트는?", a: "이 페이지는 인치·cm만 다룹니다." },
      { q: "모니터 인치는?", a: "대각선 길이 표기 참고용으로 환산만 하세요." },
      { q: "음수는?", a: "0 이상만 입력하도록 두었습니다." },
      { q: "과학 실험용으로 충분한가요?", a: "일상·업무 참고용입니다. 정밀 실험은 교정된 장비를 쓰세요." },
    ]),
  },
  {
    slug: "kg-lb",
    categoryId: "convert",
    title: "kg ↔ lb 변환",
    shortTitle: "kg·lb",
    seoTitle: "kg lb 변환기 | 킬로그램 파운드",
    ogDescription: "킬로그램과 파운드(lb)를 서로 바꿉니다.",
    description: "kg와 lb(파운드)를 양방향으로 변환합니다.",
    introText: "체중·배송·레시피 단위를 맞출 때 참고합니다.",
    metaDescription: "kg lb 환산: 표준 상수 기준 양방향. 모바일 즉시.",
    keywords: ["kg lb", "킬로그램 파운드", "파운드 변환", "lb kg"],
    bodyText: "상수는 국제적으로 많이 쓰이는 근사값입니다.",
    relatedIntro: "인치·온도·데이터 단위 변환과 이어서 쓰기 좋습니다.",
    relatedSlugs: ["inch-cm", "celsius-fahrenheit", "bmi", "area"],
    isNew: true,
    toolSections: sec(
      "kg 또는 lb 중 편한 쪽에 숫자를 입력합니다.",
      "1 lb ≈ 0.45359237 kg의 역수 관계로 환산합니다(표시는 반올림).",
      "70kg는 약 154lb 전후로 볼 수 있습니다.",
      "의료·법적 계량은 공인 저울과 규정을 따르세요.",
    ),
    faq: faq([
      { q: "스톤(st) 단위는?", a: "지원하지 않습니다." },
      { q: "온스(oz)는?", a: "무게 oz는 이 페이지에 없습니다." },
      { q: "체중계와 0.1 차이나요.", a: "반온림·표시 자릿수 차이일 수 있습니다." },
      { q: "음수는?", a: "0 이상만 입력합니다." },
      { q: "lb는 항상 파운드인가요?", a: "여기서는 국제적으로 흔한 파운드(약 0.45359237kg)를 뜻합니다." },
      { q: "골프 클럽 lb는?", a: "다른 의미일 수 있으니 문맥을 확인하세요." },
    ]),
  },
  {
    slug: "celsius-fahrenheit",
    categoryId: "convert",
    title: "섭씨 ↔ 화씨 변환",
    shortTitle: "℃·℉",
    seoTitle: "섭씨 화씨 변환기 | °C °F",
    ogDescription: "섭씨와 화씨를 실시간으로 바꿉니다.",
    description: "℃와 ℉를 양방향으로 변환합니다.",
    introText: "날씨·오븐·해외 뉴스 온도를 맞출 때 씁니다.",
    metaDescription: "섭씨 화씨 계산: °C ↔ °F. 즉시 환산, 모바일.",
    keywords: ["섭씨 화씨", "C F 변환", "온도 변환", "화씨 섭씨"],
    bodyText: "절대영도·켈빈 변환은 제공하지 않습니다.",
    relatedIntro: "단위 변환·일상 계산 도구와 함께 쓰세요.",
    relatedSlugs: ["kg-lb", "inch-cm", "world-clock", "water-intake"],
    isNew: true,
    toolSections: sec(
      "섭씨 또는 화씨 중 하나에 값을 넣습니다.",
      "°F = °C × 9/5 + 32, °C = (°F − 32) × 5/9.",
      "0℃는 32℉, 100℃는 212℉입니다.",
      "체감온도·습도 보정은 하지 않습니다.",
    ),
    faq: faq([
      { q: "음수도 되나요?", a: "네. 영하 온도도 입력할 수 있습니다." },
      { q: "오븐은?", a: "기기 표기와 레시피 단위를 맞출 때 참고만 하세요." },
      { q: "켈빈은?", a: "지원하지 않습니다." },
      { q: "소수점은?", a: "반올림되어 보일 수 있습니다." },
      { q: "체감 온도와 다르대요.", a: "바람·습도는 반영하지 않습니다." },
      { q: "날씨 앱과 0.1 차이", a: "데이터 출처·반올림 차이일 수 있습니다." },
    ]),
  },
  {
    slug: "data-unit-converter",
    categoryId: "convert",
    title: "데이터 용량 변환 (B·KB·MB·GB·TB)",
    shortTitle: "B·KB·MB",
    seoTitle: "KB MB GB TB 변환기 | 1024 기준",
    ogDescription: "바이트·킬로·메가·기가·테라를 1024배(이진) 기준으로 바꿉니다.",
    description: "B, KB, MB, GB, TB를 서로 변환합니다. 1024(2¹⁰) 배율입니다.",
    introText: "디스크·파일 크기를 익숙한 단위로 맞출 때 씁니다. 십진 GB(1000³)와 혼동하지 마세요.",
    metaDescription: "데이터 용량 환산: B KB MB GB TB, 1024 기준. 실시간, 모바일.",
    keywords: ["KB MB 변환", "GB TB", "바이트 변환", "용량 계산", "1024"],
    bodyText: "일부 저장소 표기는 1000 기준 십진 GB를 쓰기도 합니다. 견적·계약은 제품 스펙을 확인하세요.",
    relatedIntro: "JSON·Base64·텍스트 도구와 같이 데이터를 다룰 때 이어가기 좋습니다.",
    relatedSlugs: ["json-format", "base64", "char-count", "hash-generator"],
    isNew: true,
    toolSections: sec(
      "기준 단위와 숫자를 고른 뒤, 다른 단위로 읽습니다.",
      "1KB = 1024B, 1MB = 1024KB … 로 계산합니다.",
      "1048576 B는 1MB입니다.",
      "운영체제·제조사 표기와 1~2% 차이 날 수 있습니다.",
    ),
    faq: faq([
      { q: "1000이 아니라 1024인가요?", a: "이 도구는 1024(이진) 기준입니다." },
      { q: "비트(b)는?", a: "바이트 단위만 다룹니다. 비트는 8로 나누세요." },
      { q: "KiB와 같나요?", a: "KB 자리에 1024를 쓰는 의미에서는 비슷하게 이해할 수 있습니다." },
      { q: "음수는?", a: "0 이상만 입력합니다." },
      { q: "소수점이 길어요.", a: "큰 단위로 바꾸면 읽기 쉬워집니다." },
      { q: "네트워크 Mbps는?", a: "전송 속도 단위라 이 도구와 다릅니다." },
    ]),
  },
  {
    slug: "html-escape",
    categoryId: "text",
    title: "HTML 이스케이프 / 언이스케이프",
    shortTitle: "HTML 이스케이프",
    seoTitle: "HTML 이스케이프 | &lt; &gt; &amp; 변환",
    ogDescription: "특수문자를 HTML 엔티티로 바꾸거나 되돌립니다. 브라우저만 처리.",
    description: "& < > \" ' 문자를 엔티티로 바꾸거나 복원합니다.",
    introText: "템플릿·블로그·코드 샘플을 안전하게 붙여 넣을 때 씁니다.",
    metaDescription: "HTML escape unescape: 기본 엔티티 변환·복사. 로컬 처리.",
    keywords: ["HTML 이스케이프", "엔티티 변환", "특수문자 이스케이프", "unescape"],
    bodyText: "모든 유니코드 엔티티를 완벽히 복원하지는 않습니다. 숫자 엔티티는 필요 시 수동으로 확인하세요.",
    relatedIntro: "URL 인코딩·슬러그·JSON과 같은 편집 흐름에서 쓰세요.",
    relatedSlugs: ["url-encode", "slugify", "json-format", "whitespace"],
    isNew: true,
    toolSections: sec(
      "모드를 ‘이스케이프’ 또는 ‘언이스케이프’로 고르고 텍스트를 넣습니다.",
      "& < > \" ' 중심으로 바꿉니다.",
      "<div> 같은 문자열을 이스케이프해 볼 수 있습니다.",
      "실제 XSS 방어는 서버·프레임워크의 검증·이스케이프 정책이 필요합니다.",
    ),
    faq: faq([
      { q: "&# 숫자 엔티티는?", a: "기본 변환만 지원합니다." },
      { q: "한 번 더 이스케이프하면?", a: "의도에 따라 중첩될 수 있으니 단계를 확인하세요." },
      { q: "Markdown과 같나요?", a: "HTML 엔티티만 다룹니다." },
      { q: "서버에 저장되나요?", a: "아니요." },
      { q: "따옴표만 바꾸고 싶어요.", a: "결과에서 필요한 부분만 복사해 쓰세요." },
      { q: "전체 HTML sanitize는?", a: "전용 라이브러리·서버 필터를 쓰세요." },
    ]),
  },
  {
    slug: "line-dedupe",
    categoryId: "text",
    title: "줄 단위 중복 제거",
    shortTitle: "줄 중복 제거",
    seoTitle: "줄 중복 제거 | 목록 정리",
    ogDescription: "줄바꿈으로 구분한 목록에서 중복 줄을 빼고 순서를 유지합니다.",
    description: "같은 내용의 줄을 한 번만 남깁니다. 첫 등장 순서를 유지합니다.",
    introText: "메일·엑셀에서 붙여 온 목록을 정리할 때 씁니다.",
    metaDescription: "줄 중복 제거: 순서 유지, trim 옵션. 브라우저만, 복사 가능.",
    keywords: ["줄 중복 제거", "목록 중복", "uniq", "라인 정리"],
    bodyText: "대소문자를 다른 줄로 볼지 여부는 옵션으로 맞춥니다.",
    relatedIntro: "공백 정리·글자 수·슬러그 작업과 이어서 쓰기 좋습니다.",
    relatedSlugs: ["whitespace", "char-count", "slugify", "json-format"],
    isNew: true,
    toolSections: sec(
      "텍스트를 붙여 넣고 옵션을 고른 뒤 결과를 복사합니다.",
      "줄 단위로만 비교하며, 처음 나온 줄을 남깁니다.",
      "같은 이메일이 두 번 나온 목록을 한 번씩만 남길 수 있습니다.",
      "순서를 무작위로 섞지는 않습니다.",
    ),
    faq: faq([
      { q: "대소문자 무시하고 중복 제거는?", a: "옵션에서 대소문자 무시 비교를 켤 수 있습니다." },
      { q: "정렬은?", a: "정렬하지 않고 순서만 유지합니다." },
      { q: "빈 줄은?", a: "무시 옵션을 끄면 빈 줄도 한 줄로 취급할 수 있습니다." },
      { q: "단어 중복은?", a: "줄 단위만 다룹니다." },
      { q: "CSV 컬럼 중복은?", a: "이 도구는 줄 전체만 비교합니다." },
      { q: "서버 전송?", a: "하지 않습니다." },
    ]),
  },
];
