import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));

const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "동작 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const phase3Tools: ToolDefinition[] = [
  {
    slug: "image-compressor",
    categoryId: "utility",
    title: "이미지 압축",
    shortTitle: "이미지 압축",
    seoTitle: "이미지 압축기 | JPG PNG WebP",
    ogDescription: "이미지를 브라우저에서만 줄입니다. 압축 전후 용량·비율 유지·다운로드.",
    description: "JPG·PNG·WebP 등 이미지 파일을 업로드해 용량을 줄입니다.",
    introText: "웹 업로드·메일 첨부 전에 파일을 가볍게 할 때 씁니다. 서버로 업로드하지 않습니다.",
    metaDescription: "이미지 압축: 드래그앤드롭·용량 비교·다운로드. 로컬만 처리.",
    keywords: ["이미지 압축", "사진 줄이기", "용량 줄이기", "jpg 압축"],
    bodyText: "과도한 압축은 화질을 떨어뜨립니다. 중요한 원본은 따로 보관하세요.",
    relatedIntro: "PDF·파비콘·QR과 같이 이미지를 다루는 흐름에 넣기 좋습니다.",
    relatedSlugs: ["favicon-generator", "pdf-merge-split", "qr-code-generator", "base64"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "파일을 선택하거나 끌어다 놓습니다. 품질 슬라이더로 크기와 화질의 균형을 맞춥니다.",
      "canvas를 통해 픽셀을 다시 인코딩하는 방식입니다.",
      "큰 사진 한 장으로 시험해 보세요.",
      "RAW·TIFF 등 일부 형식은 브라우저가 읽지 못할 수 있습니다.",
    ),
    faq: faq([
      { q: "원본이 삭제되나요?", a: "서버에 올리지 않으며, 다운로드 파일을 직접 저장해야 합니다." },
      { q: "PNG도 줄어드나요?", a: "가능하지만 JPG보다 효과가 작을 수 있습니다." },
      { q: "해상도는?", a: "긴 변 기준으로 최대 크기를 제한할 수 있습니다." },
      { q: "용량이 늘어났어요.", a: "원본이 이미 작거나 투명 PNG를 JPG로 바꾸는 경우 등이 있습니다." },
      { q: "여러 장은?", a: "한 번에 한 장씩 처리합니다." },
      { q: "개인정보 사진도?", a: "처리는 로컬이지만 민감 사진은 신중히 다루세요." },
    ]),
  },
  {
    slug: "pdf-merge-split",
    categoryId: "utility",
    title: "PDF 병합 · 페이지 나누기",
    shortTitle: "PDF",
    seoTitle: "PDF 병합 분할 | 브라우저",
    ogDescription: "여러 PDF를 한 파일로 합치거나, 한 PDF를 페이지별로 나눕니다. 업로드는 브라우저만.",
    description: "PDF 파일을 순서대로 병합하거나 페이지마다 나누어 저장합니다.",
    introText: "간단한 문서 합치기·페이지 추출에 씁니다. 스캔 품질·암호화 문서는 환경에 따라 실패할 수 있습니다.",
    metaDescription: "PDF 병합·분할: pdf-lib 로컬 처리, ZIP 다운로드. 로그인 없음.",
    keywords: ["PDF 병합", "PDF 분할", "pdf 합치기", "페이지 추출"],
    bodyText: "전자문서 법적 효력·서명 검증은 전용 뷰어를 쓰세요.",
    relatedIntro: "이미지 압축·파비콘·Base64와 같이 파일을 다룰 때 이어가기 좋습니다.",
    relatedSlugs: ["image-compressor", "favicon-generator", "base64", "json-format"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "병합: 파일을 여러 개 고르고 순서대로 합칩니다. 분할: 한 파일을 페이지별 PDF로 ZIP에 담습니다.",
      "pdf-lib로 페이지를 읽고 씁니다.",
      "짧은 보고서 두 개를 합쳐 보거나, 긴 PDF를 페이지별로 나눠 보세요.",
      "암호·폼·특수 객체가 있으면 결과가 달라질 수 있습니다.",
    ),
    faq: faq([
      { q: "암호 걸린 PDF는?", a: "열 수 없으면 분석하지 못합니다." },
      { q: "순서를 바꿀 수 있나요?", a: "파일 선택 순서가 병합 순서입니다. 다시 고르면 됩니다." },
      { q: "용량 제한은?", a: "브라우저 메모리에 따라 큰 파일은 실패할 수 있습니다." },
      { q: "서버에 올라가나요?", a: "아니요." },
      { q: "워터마크는?", a: "제거하지 않습니다." },
      { q: "페이지 일부만?", a: "이 버전은 전체 페이지 분할 중심입니다. 필요하면 여러 번 나누세요." },
    ]),
  },
  {
    slug: "favicon-generator",
    categoryId: "utility",
    title: "파비콘 만들기",
    shortTitle: "파비콘",
    seoTitle: "파비콘 생성기 | PNG 16 32 48",
    ogDescription: "이미지를 넣어 파비콘 크기 PNG로 저장합니다. 브라우저에서만 처리.",
    description: "정사각형에 가까운 이미지를 16·32·48px PNG로 만듭니다.",
    introText: "간단한 사이트 아이콘을 만들 때 씁니다. 복잡한 ICO 다중 해상도는 전용 툴을 쓰세요.",
    metaDescription: "파비콘 PNG: 16·32·48px 다운로드. 로컬만, 업로드 없음.",
    keywords: ["파비콘", "favicon", "아이콘 만들기", "png 아이콘"],
    bodyText: "투명 PNG를 넣으면 배경이 비어 보일 수 있습니다. 필요하면 배경 있는 이미지를 쓰세요.",
    relatedIntro: "이미지 압축·QR·Base64와 같이 에셋을 준비할 때 쓰기 좋습니다.",
    relatedSlugs: ["image-compressor", "qr-code-generator", "base64", "html-escape"],
    isNew: true,
    toolSections: sec(
      "이미지를 선택하면 미리보기와 크기별 저장 버튼이 나타납니다.",
      "canvas로 축소 후 PNG로 내보냅니다.",
      "로고 원본을 넣고 32px 결과를 받아 보세요.",
      "브라우더·OS마다 favicon 규칙이 다를 수 있습니다.",
    ),
    faq: faq([
      { q: "ICO 파일은?", a: "이 페이지는 PNG만 제공합니다." },
      { q: "직사각형 이미지는?", a: "중앙 기준으로 잘라 정사각형에 맞춥니다." },
      { q: "SVG는?", a: "브라우저가 읽을 수 있으면 시도하지만 실패할 수 있습니다." },
      { q: "저작권은?", a: "사용 권한은 직접 확인하세요." },
      { q: "Retina 대응은?", a: "큰 크기 PNG를 head에 여러 개 링크하는 방식을 검토하세요." },
      { q: "서버 업로드?", a: "하지 않습니다." },
    ]),
  },
];
