import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));

const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "동작 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const phase5Tools: ToolDefinition[] = [
  {
    slug: "image-resizer",
    categoryId: "utility",
    title: "이미지 리사이저",
    shortTitle: "리사이저",
    seoTitle: "이미지 리사이저 | 너비·높이 조절",
    ogDescription: "이미지 크기를 픽셀 단위로 조절합니다. 비율 유지 옵션 제공.",
    description: "이미지의 너비·높이를 조절해 PNG로 저장합니다.",
    introText: "썸네일·업로드용 규격에 맞춰 이미지를 빠르게 리사이즈할 때 씁니다.",
    metaDescription: "이미지 리사이즈: 비율 유지·크기 지정·PNG 다운로드. 브라우저 로컬 처리.",
    keywords: ["이미지 리사이즈", "이미지 크기 조절", "썸네일", "픽셀 변경"],
    bodyText: "원본 비율을 유지하지 않으면 이미지가 찌그러질 수 있습니다.",
    relatedIntro: "압축·포맷 변환·PDF 변환과 함께 쓰면 이미지 작업 흐름이 깔끔해집니다.",
    relatedSlugs: ["image-compressor", "image-format-converter", "image-to-pdf", "favicon-generator"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "가로·세로 픽셀을 입력하고 이미지를 선택합니다. 비율 유지 옵션을 켜면 원본 비율을 기준으로 자동 보정합니다.",
      "canvas로 이미지를 다시 그려 PNG로 저장합니다.",
      "1080×1080 썸네일 규격을 자주 쓰면 예시 버튼으로 빠르게 맞출 수 있습니다.",
      "업스케일은 화질을 높이지 않습니다. 원본보다 큰 크기로 키우면 선명도가 떨어질 수 있습니다.",
    ),
    faq: faq([
      { q: "원본 파일이 바뀌나요?", a: "원본은 유지되고 결과 파일만 새로 저장됩니다." },
      { q: "JPG로 저장할 수 있나요?", a: "이 도구는 PNG 저장 중심입니다. 포맷 변환은 별도 도구를 사용하세요." },
      { q: "비율 유지가 꼭 필요한가요?", a: "인물·제품 사진은 보통 켜는 것이 자연스럽습니다." },
      { q: "서버에 업로드되나요?", a: "아니요. 브라우저에서만 처리합니다." },
      { q: "HEIC 파일은?", a: "브라우저가 읽지 못하면 실패할 수 있습니다." },
      { q: "배경 투명도는?", a: "PNG 출력은 투명 배경을 유지할 수 있습니다." },
    ]),
  },
  {
    slug: "image-format-converter",
    categoryId: "utility",
    title: "이미지 포맷 변환",
    shortTitle: "포맷 변환",
    seoTitle: "이미지 포맷 변환 | JPG PNG WebP",
    ogDescription: "이미지를 JPG·PNG·WebP로 변환해 저장합니다.",
    description: "이미지 파일을 JPG/PNG/WebP 중 원하는 형식으로 변환합니다.",
    introText: "업로드 정책이나 용량 목표에 맞춰 이미지 포맷을 바꿀 때 씁니다.",
    metaDescription: "이미지 포맷 변환: JPEG PNG WEBP, 품질 옵션·다운로드. 로컬 처리.",
    keywords: ["이미지 포맷 변환", "jpg png webp", "사진 형식 변환", "webp 변환"],
    bodyText: "PNG는 무손실 중심이고, JPEG·WebP는 품질 값에 따라 용량·화질이 달라집니다.",
    relatedIntro: "압축·리사이즈 후 포맷을 바꾸면 업로드 품질 관리가 쉬워집니다.",
    relatedSlugs: ["image-compressor", "image-resizer", "image-to-pdf", "favicon-generator"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "출력 포맷을 고르고 이미지를 업로드하면 변환 결과를 미리볼 수 있습니다.",
      "canvas 인코딩을 사용하며 JPEG/WEBP는 품질 옵션을 반영합니다.",
      "사진은 WebP 0.8~0.9, 투명 로고는 PNG를 권장합니다.",
      "브라우저마다 WebP 지원·인코딩 품질이 조금 다를 수 있습니다.",
    ),
    faq: faq([
      { q: "투명 배경은 유지되나요?", a: "PNG는 유지되지만 JPEG는 배경이 채워질 수 있습니다." },
      { q: "품질 값은 언제 쓰나요?", a: "JPEG/WEBP에만 의미가 있고 PNG에는 영향이 거의 없습니다." },
      { q: "용량이 오히려 커졌어요.", a: "원본과 포맷 특성에 따라 커질 수 있습니다." },
      { q: "여러 장 일괄 변환은?", a: "현재는 한 장씩 처리합니다." },
      { q: "서버 전송?", a: "하지 않습니다." },
      { q: "색감이 달라 보여요.", a: "색공간·브라우저 렌더 차이일 수 있습니다." },
    ]),
  },
  {
    slug: "image-to-pdf",
    categoryId: "utility",
    title: "이미지 → PDF 변환",
    shortTitle: "이미지→PDF",
    seoTitle: "이미지 PDF 변환기 | JPG PNG to PDF",
    ogDescription: "여러 이미지를 하나의 PDF로 합쳐 저장합니다.",
    description: "여러 JPG/PNG 이미지를 한 개 PDF 파일로 만듭니다.",
    introText: "서류 제출용 스캔 이미지 묶기나 공유용 파일 정리에 유용합니다.",
    metaDescription: "이미지→PDF: 여러 장을 순서대로 PDF로 결합, 브라우저 로컬 처리.",
    keywords: ["이미지 pdf", "jpg to pdf", "png pdf 변환", "사진 pdf 만들기"],
    bodyText: "선택한 순서가 페이지 순서가 됩니다. 필요하면 파일명을 숫자로 정렬해 선택하세요.",
    relatedIntro: "PDF 병합/분할·PDF→이미지와 함께 문서 변환 흐름을 구성할 수 있습니다.",
    relatedSlugs: ["pdf-merge-split", "pdf-to-image", "image-compressor", "image-resizer"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "여러 이미지를 선택하면 선택 순서대로 PDF 페이지가 생성됩니다.",
      "pdf-lib로 이미지 바이트를 임베드하고 페이지 크기를 이미지 크기에 맞춥니다.",
      "영수증·문서 사진 여러 장을 한 PDF로 묶어 제출 파일을 만들 수 있습니다.",
      "아주 큰 원본 이미지가 많으면 메모리 사용량이 커질 수 있습니다.",
    ),
    faq: faq([
      { q: "페이지 크기(A4)로 맞출 수 있나요?", a: "현재는 원본 이미지 크기 기준입니다." },
      { q: "HEIC도 되나요?", a: "브라우저와 pdf-lib 지원 여부에 따라 실패할 수 있습니다." },
      { q: "순서가 틀렸어요.", a: "파일 선택 순서를 다시 맞춰 선택해 주세요." },
      { q: "서버 업로드?", a: "하지 않습니다." },
      { q: "워터마크를 넣을 수 있나요?", a: "현재 버전은 지원하지 않습니다." },
      { q: "암호 PDF로 만들 수 있나요?", a: "지원하지 않습니다." },
    ]),
  },
  {
    slug: "pdf-to-image",
    categoryId: "utility",
    title: "PDF → 이미지 변환",
    shortTitle: "PDF→이미지",
    seoTitle: "PDF 이미지 변환기 | 페이지별 PNG",
    ogDescription: "PDF 각 페이지를 PNG로 추출해 ZIP으로 저장합니다.",
    description: "PDF 페이지를 PNG 이미지로 변환해 ZIP 파일로 받습니다.",
    introText: "문서 일부를 이미지로 공유하거나 썸네일을 만들 때 사용합니다.",
    metaDescription: "PDF→PNG: 페이지별 변환, ZIP 다운로드, 브라우저 로컬 처리.",
    keywords: ["pdf to image", "pdf png 변환", "pdf 페이지 추출", "pdf 이미지"],
    bodyText: "브라우저 성능을 위해 페이지 수가 많으면 일부 페이지만 변환할 수 있습니다.",
    relatedIntro: "이미지→PDF, PDF 병합·분할과 이어서 문서 변환 흐름을 완성할 수 있습니다.",
    relatedSlugs: ["image-to-pdf", "pdf-merge-split", "image-compressor", "image-format-converter"],
    isNew: true,
    featured: true,
    toolSections: sec(
      "PDF를 선택하면 페이지를 순서대로 렌더링해 PNG ZIP으로 저장합니다.",
      "pdfjs-dist 렌더러를 사용하고, 브라우저 메모리 보호를 위해 최대 변환 페이지를 제한합니다.",
      "슬라이드 PDF를 PNG로 뽑아 썸네일·공유 이미지를 만들 수 있습니다.",
      "벡터·폰트·투명도에 따라 원문과 보이는 결과가 조금 다를 수 있습니다.",
    ),
    faq: faq([
      { q: "모든 페이지가 변환되지 않아요.", a: "성능 보호를 위해 최대 페이지 제한이 있습니다." },
      { q: "해상도를 바꿀 수 있나요?", a: "현재는 기본 2배 렌더 스케일을 사용합니다." },
      { q: "암호화 PDF는?", a: "열리지 않으면 변환할 수 없습니다." },
      { q: "서버 업로드?", a: "하지 않습니다." },
      { q: "JPG로 저장할 수 있나요?", a: "현재는 PNG ZIP 출력만 지원합니다." },
      { q: "변환이 느려요.", a: "페이지 수·해상도·기기 성능에 따라 시간이 늘어납니다." },
    ]),
  },
];

