import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));
const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "동작 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const phase6Tools: ToolDefinition[] = [
  {
    slug: "sales-fee-calculator",
    categoryId: "calculator",
    title: "판매 수수료 계산기",
    shortTitle: "판매 수수료",
    description: "판매가·수수료율·고정 수수료로 정산 예상금을 계산합니다.",
    metaDescription: "판매 수수료 계산기: 총매출, 총수수료, 정산 예상금 산출.",
    relatedSlugs: ["margin", "unit-cost-with-shipping", "roi-calculator", "exchange-rate"],
    keywords: ["판매 수수료", "정산 계산", "스마트스토어 수수료", "마켓 수수료"],
    seoTitle: "판매 수수료 계산기 | 정산 예상금",
    ogDescription: "총매출·수수료·정산금액을 빠르게 계산합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "정확한 정산과 같은가요?", a: "플랫폼 세부 정책은 반영되지 않은 단순 모델입니다." }]),
    toolSections: sec("판매가, 수량, 수수료율을 입력합니다.", "정산금 = 총매출 - (비율수수료 + 고정수수료)", "39,000원 상품 10개, 수수료 10%", "실제 정산 기준과 차이가 날 수 있습니다."),
  },
  {
    slug: "unit-cost-with-shipping",
    categoryId: "calculator",
    title: "배송비 포함 단가 계산기",
    shortTitle: "단가 계산",
    description: "상품 원가와 배송비를 합산해 개당 원가를 계산합니다.",
    metaDescription: "배송비 포함 원가를 수량 기준 개당 단가로 환산합니다.",
    relatedSlugs: ["sales-fee-calculator", "margin", "discount", "roi-calculator"],
    keywords: ["단가 계산", "배송비 포함 원가", "개당 원가"],
    seoTitle: "배송비 포함 단가 계산기",
    ogDescription: "총원가와 개당 원가를 빠르게 확인합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "부가세 포함도 되나요?", a: "입력 금액 기준을 동일하게 맞추면 가능합니다." }]),
    toolSections: sec("상품 원가, 배송비, 수량을 넣습니다.", "개당 원가 = (상품원가+배송비)/수량", "총 110,000원, 수량 20개", "포장비·반품비는 별도 반영하세요."),
  },
  {
    slug: "roi-calculator",
    categoryId: "calculator",
    title: "ROI 계산기",
    shortTitle: "ROI",
    description: "투입비용 대비 수익률(ROI)을 계산합니다.",
    metaDescription: "ROI 계산기: 순이익과 수익률을 한 번에 확인.",
    relatedSlugs: ["break-even", "margin", "sales-fee-calculator", "percent"],
    keywords: ["ROI", "수익률 계산", "투자 수익률"],
    seoTitle: "ROI 계산기 | 수익률 계산",
    ogDescription: "투입비용과 회수금액으로 ROI를 계산합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "ROAS와 같은가요?", a: "아닙니다. ROAS는 광고비 대비 매출, ROI는 비용 대비 순이익 기준입니다." }]),
    toolSections: sec("비용과 회수금액을 입력합니다.", "ROI=(순이익/비용)×100", "100만원 투자, 130만원 회수", "세금·고정비 포함 여부를 입력 전에 정하세요."),
  },
  {
    slug: "break-even",
    categoryId: "calculator",
    title: "손익분기점 계산기",
    shortTitle: "손익분기점",
    description: "고정비·판매단가·변동비로 손익분기점 수량과 매출을 계산합니다.",
    metaDescription: "손익분기점(BEP) 수량과 매출 계산.",
    relatedSlugs: ["roi-calculator", "margin", "sales-fee-calculator", "unit-cost-with-shipping"],
    keywords: ["손익분기점", "BEP", "고정비 계산"],
    seoTitle: "손익분기점 계산기 | BEP 수량",
    ogDescription: "판매단가와 변동비로 손익분기점을 계산합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "판매단가가 변동비보다 낮으면?", a: "손익분기점을 계산할 수 없습니다." }]),
    toolSections: sec("고정비·판매단가·변동비를 넣습니다.", "BEP수량=고정비/(판매단가-변동비)", "고정비 100만원, 단가 1.5만원, 변동비 7천원", "현실에서는 추가 비용항목을 더 반영해야 합니다."),
  },
  {
    slug: "jeonse-wolse",
    categoryId: "calculator",
    title: "전월세 환산 계산기",
    shortTitle: "전월세",
    description: "보증금과 월세를 환산율 기준으로 서로 환산합니다.",
    metaDescription: "전월세 환산 계산기: 보증금↔월세 참고 계산.",
    relatedSlugs: ["loan", "area", "break-even", "percent"],
    keywords: ["전월세 계산", "보증금 환산", "월세 환산"],
    seoTitle: "전월세 환산 계산기",
    ogDescription: "보증금과 월세를 환산율로 계산합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "법적 계산과 동일한가요?", a: "계약·지역 관행에 따라 다를 수 있는 참고 계산입니다." }]),
    toolSections: sec("보증금·월세·환산율을 입력합니다.", "연환산율 기준으로 월세/보증금을 계산합니다.", "보증금 1억, 환산율 4%", "실제 계약 조건과 차이가 날 수 있습니다."),
  },
  {
    slug: "meeting-time",
    categoryId: "utility",
    title: "회의 시간 계산기",
    shortTitle: "회의 시간",
    description: "회의 참석 인원과 시간을 곱해 총 투입 인시를 계산합니다.",
    metaDescription: "회의 시간 계산기: 총 인분·인시 계산.",
    relatedSlugs: ["timer-stopwatch", "todo-checklist", "roi-calculator", "break-even"],
    keywords: ["회의 시간", "인시 계산", "생산성"],
    seoTitle: "회의 시간 계산기",
    ogDescription: "참석 인원과 회의시간으로 총 인시를 계산합니다.",
    isNew: true,
    featured: false,
    faq: faq([{ q: "회의비용까지 계산되나요?", a: "현재는 시간량(인시)만 계산합니다." }]),
    toolSections: sec("참석 인원과 회의 시간을 입력합니다.", "총 인시=인원×시간", "8명×60분=8인시", "초과근무/시급 계산은 별도 도구와 함께 보세요."),
  },
  {
    slug: "title-length",
    categoryId: "text",
    title: "제목 길이 체크",
    shortTitle: "제목 길이",
    description: "제목 글자 수를 기준 길이와 비교해 남은 수를 계산합니다.",
    metaDescription: "제목 길이 체크: 기준 대비 남은 글자 확인.",
    relatedSlugs: ["meta-description-length", "char-count", "hashtag-cleaner", "slugify"],
    keywords: ["제목 길이", "타이틀 글자수", "콘텐츠 제목"],
    seoTitle: "제목 길이 체크 도구",
    ogDescription: "제목 길이를 빠르게 확인하고 초과 여부를 점검합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "검색 결과 노출 글자수와 같나요?", a: "기기·검색어에 따라 표시 길이는 달라질 수 있습니다." }]),
    toolSections: sec("제목과 기준 길이를 입력합니다.", "입력 문자 수를 계산하고 기준과 비교합니다.", "기준 60자", "문장 의미를 먼저 유지하세요."),
  },
  {
    slug: "meta-description-length",
    categoryId: "text",
    title: "메타 설명 길이 체크",
    shortTitle: "메타 설명",
    description: "메타 설명 길이를 체크해 권장 범위와 비교합니다.",
    metaDescription: "메타 설명 길이 체크: 권장 80~160자 비교.",
    relatedSlugs: ["title-length", "char-count", "slugify", "json-format"],
    keywords: ["메타 설명", "meta description", "SEO 길이"],
    seoTitle: "메타 설명 길이 체크 도구",
    ogDescription: "메타 설명 문구 길이를 빠르게 확인합니다.",
    isNew: true,
    featured: true,
    faq: faq([{ q: "정확한 노출 길이는?", a: "검색엔진·기기 환경에 따라 다릅니다." }]),
    toolSections: sec("설명 문구를 입력합니다.", "문자 수를 계산하고 권장 범위와 비교합니다.", "80~160자 권장", "과도한 키워드 반복은 피하세요."),
  },
  {
    slug: "hashtag-cleaner",
    categoryId: "text",
    title: "해시태그 정리기",
    shortTitle: "해시태그",
    description: "해시태그 중복을 제거하고 공백·쉼표를 정리합니다.",
    metaDescription: "해시태그 정리기: 중복 제거·형식 정리.",
    relatedSlugs: ["title-length", "meta-description-length", "char-count", "line-dedupe"],
    keywords: ["해시태그 정리", "hashtag", "중복 제거"],
    seoTitle: "해시태그 정리기",
    ogDescription: "중복 없는 해시태그 문자열을 빠르게 만듭니다.",
    isNew: true,
    featured: false,
    faq: faq([{ q: "대소문자도 중복으로 보나요?", a: "네, 대소문자 구분 없이 중복을 제거합니다." }]),
    toolSections: sec("해시태그 문자열을 붙여넣습니다.", "공백/쉼표 분리 후 # 접두를 맞추고 중복 제거합니다.", "#tool #Tool #seo", "플랫폼별 개수 제한은 별도로 확인하세요."),
  },
];

