import type { ToolDefinition } from "./types";

const faq = (items: { q: string; a: string }[]) =>
  items.map((x) => ({ question: x.q, answer: x.a }));

const sec = (a: string, b: string, c: string, d: string) => [
  { title: "어떻게 쓰나요?", content: a },
  { title: "계산 기준", content: b },
  { title: "예시", content: c },
  { title: "주의할 점", content: d },
];

export const batch3RestTools: ToolDefinition[] = [
  {
    slug: "speed-converter",
    categoryId: "convert",
    title: "속도 환산 (km/h ↔ mph 등)",
    shortTitle: "속도",
    seoTitle: "속도 환산 | km/h mph m/s 노트",
    ogDescription: "km/h를 기준으로 mph·m/s·노트를 함께 봅니다. 로그인 없이.",
    description: "km/h 입력 시 mph, m/s, 노트(해리/시)로 변환합니다.",
    introText: "자동차·항공·달리기 단위를 맞출 때 쓰는 참고용입니다.",
    metaDescription: "속도 환산: km/h mph m/s 노트. 단위 변환, 모바일 즉시.",
    keywords: ["속도 환산", "km/h mph", "m/s", "노트", "시속"],
    bodyText: "해상·항공 표준에 따라 정의가 다를 수 있습니다.",
    relatedIntro: "연비·페이스·날짜 도구와 함께 쓰면 수치 비교가 쉽습니다.",
    relatedSlugs: ["fuel-converter", "pace-calculator", "area", "percent"],
    toolSections: sec(
      "km/h를 입력합니다.",
      "mph = km/h × 0.621371, m/s = km/h ÷ 3.6, 노트 = km/h ÷ 1.852.",
      "100km/h이면 mph와 m/s를 동시에 볼 수 있습니다.",
      "정밀 항법에는 전용 도구를 쓰세요.",
    ),
    faq: faq([
      { q: "mph가 뭔가요?", a: "미국 등에서 쓰는 마일/시간입니다." },
      { q: "노트는?", a: "해리(1.852km)를 1시간에 가는 속도입니다." },
      { q: "음속은?", a: "이 도구는 제공하지 않습니다." },
      { q: "소수점은?", a: "표시용 반올림일 수 있습니다." },
      { q: "뛰는 속도도?", a: "같은 단위 변환입니다." },
      { q: "GPS 단위는?", a: "기기 설정에 따릅니다." },
    ]),
  },
  {
    slug: "unix-timestamp",
    categoryId: "dev",
    title: "Unix 시간 변환",
    shortTitle: "Unix",
    seoTitle: "Unix 시간 변환기 | 초·날짜 상호 변환",
    ogDescription: "Unix 초(또는 ms)를 날짜로, 또는 문자열을 시각으로 해석합니다.",
    description: "Unix 시간과 사람이 읽는 날짜를 서로 변환합니다.",
    introText: "API·로그·DB 타임스탬프를 확인할 때 쓰는 도구입니다.",
    metaDescription: "Unix 시간: 초·ms ↔ 로컬 날짜. 개발 참고, 모바일 즉시.",
    keywords: ["Unix 시간", "타임스탬프", "epoch", "UTC 변환"],
    bodyText: "로컬 타임존은 브라우저 설정을 따릅니다.",
    relatedIntro: "세계 시계·날짜 계산기와 같이 쓰세요.",
    relatedSlugs: ["world-clock", "date", "json-format", "base64"],
    toolSections: sec(
      "숫자만 넣으면 초(ms 자릿수로 추정)로 해석하고, 날짜 문자열이면 파싱합니다.",
      "13자리면 ms, 10자리면 초로 둡니다.",
      "1735123456 같은 값을 넣어 확인합니다.",
      "연도 2038 문제 등은 환경에 따라 다릅니다.",
    ),
    faq: faq([
      { q: "UTC로 보고 싶어요.", a: "브라우저 로컬로 표시합니다. UTC는 별도 환경이 필요합니다." },
      { q: "ms와 초 구분은?", a: "자릿수로 추정합니다. 틀리면 직접 나누세요." },
      { q: "Excel 날짜는?", a: "이 도구는 표준 문자열을 우선합니다." },
      { q: "음수 타임스탬프는?", a: "1970년 이전일 수 있습니다." },
      { q: "서버와 1초 차이요.", a: "동기화·NTP 문제일 수 있습니다." },
      { q: "보안 로그에 써도 되나요?", a: "민감 데이터는 오프라인 환경을 권장합니다." },
    ]),
  },
  {
    slug: "uuid-generator",
    categoryId: "dev",
    title: "UUID 생성기",
    shortTitle: "UUID",
    seoTitle: "UUID 생성기 | v4 랜덤",
    ogDescription: "UUID v4를 한 번에 여러 개 생성합니다. 저장하지 않습니다.",
    description: "crypto.randomUUID() 기반 UUID를 여러 개 만듭니다.",
    introText: "테스트 데이터·임시 ID가 필요할 때 쓰는 도구입니다.",
    metaDescription: "UUID 생성: v4 랜덤, 개수 선택. 로컬만, 모바일 즉시.",
    keywords: ["UUID 생성", "UUID v4", "고유 ID", "랜덤 UUID"],
    bodyText: "생성값은 서버에 보내지 않지만, 화면 공유 시 주의하세요.",
    relatedIntro: "비밀번호·난수·해시·Base64와 연계해 쓰세요.",
    relatedSlugs: ["hash-generator", "password-generator", "random-number", "random-picker", "unix-timestamp"],
    toolSections: sec(
      "개수를 정하고 생성을 누릅니다.",
      "RFC 4124 v4 무작위 형식을 목표로 합니다.",
      "여러 개를 한 번에 복사해 테스트에 붙일 수 있습니다.",
      "분산 환경에서 중복 확률은 사실상 무시합니다.",
    ),
    faq: faq([
      { q: "v1은?", a: "이 페이지는 v4만 생성합니다." },
      { q: "DB에 넣어도 되나요?", a: "스키마·인덱스 규칙을 확인하세요." },
      { q: "같은 값이 나올 수 있나요?", a: "이론상 가능하지만 매우 드뭅니다." },
      { q: "오프라인에서?", a: "crypto가 지원되면 동작합니다." },
      { q: "대문자로?", a: "표시 형식만 다를 수 있습니다." },
      { q: "보안 토큰으로?", a: "용도에 맞는 전용 생성기를 쓰세요." },
    ]),
  },
  {
    slug: "color-converter",
    categoryId: "dev",
    title: "색상 피커 · HEX · RGB · HSL",
    shortTitle: "색상",
    seoTitle: "색상 피커 | HEX RGB HSL 변환",
    ogDescription: "피커·HEX·RGB·HSL을 서로 맞춥니다. 미리보기 포함.",
    description: "색상 피커와 HEX·RGB·HSL 입력으로 색을 맞춥니다.",
    introText: "웹·디자인 작업에서 색 코드를 맞출 때 쓰는 도구입니다.",
    metaDescription: "HEX RGB HSL 변환, 색 미리보기. 개발·디자인, 모바일 즉시.",
    keywords: ["HEX RGB", "색상 변환", "컬러피커", "HSL"],
    bodyText: "모니터·색공간에 따라 실제와 다를 수 있습니다.",
    relatedIntro: "Base64·URL 인코딩과 같이 웹 작업 흐름에 넣으세요.",
    relatedSlugs: ["base64", "url-encode", "slugify", "regex-tester"],
    toolSections: sec(
      "#RRGGBB 형식으로 입력합니다.",
      "HEX를 RGB로 풀고, HSL은 근사값입니다.",
      "#4f46e5 같은 브랜드 컬러를 넣어 볼 수 있습니다.",
      "CMYK·Pantone은 지원하지 않습니다.",
    ),
    faq: faq([
      { q: "3자리 #RGB는?", a: "6자리로 풀어 넣어 주세요." },
      { q: "투명도는?", a: "RGBA/HEX8은 이 페이지에서 다루지 않습니다." },
      { q: "HSL이 정확한가요?", a: "일반적인 변환식입니다." },
      { q: "인쇄 색은?", a: "별도 프로파일이 필요합니다." },
      { q: "다크모드와?", a: "미리보기는 브라우저에서만 보입니다." },
      { q: "피그마와 다릅니다.", a: "반올림·색공간 차이일 수 있습니다." },
    ]),
  },
  {
    slug: "regex-tester",
    categoryId: "dev",
    title: "정규식 테스트",
    shortTitle: "정규식",
    seoTitle: "정규식 테스트기 | JavaScript RegExp",
    ogDescription: "패턴·플래그·본문으로 매치 결과를 확인합니다. 브라우저만.",
    description: "JavaScript RegExp로 매칭 위치와 결과를 나열합니다.",
    introText: "검색·검증 로직을 짤 때 쓰는 참고용입니다.",
    metaDescription: "정규식 테스트: 패턴 매치, 플래그. JS 기준, 모바일 즉시.",
    keywords: ["정규식", "regex", "RegExp", "패턴 매칭"],
    bodyText: "엔진마다 문법이 다를 수 있습니다. 프로덕션은 테스트를 충분히 하세요.",
    relatedIntro: "슬러그·URL·JSON 도구와 함께 쓰기 좋습니다.",
    relatedSlugs: ["slugify", "url-encode", "json-format", "char-count"],
    toolSections: sec(
      "패턴, 플래그(g i m 등), 본문을 넣습니다.",
      "JavaScript의 RegExp 규칙을 따릅니다.",
      "이메일 형식 등을 빠르게 테스트할 수 있습니다.",
      "ReDoS 등 위험한 패턴은 주의하세요.",
    ),
    faq: faq([
      { q: "플래그가 안 먹어요.", a: "허용 문자만 통과합니다." },
      { q: "Python과 다릅니다.", a: "JS 표준을 따릅니다." },
      { q: "전방 탐색은?", a: "JS가 지원하는 범위에서 동작합니다." },
      { q: "매치가 너무 많아요.", a: "g 플래그를 끄거나 패턴을 좁히세요." },
      { q: "한글은?", a: "유니코드 모드가 필요할 수 있습니다." },
      { q: "보안 검사용인가요?", a: "아니요. 참고용입니다." },
    ]),
  },
  {
    slug: "binary-converter",
    categoryId: "dev",
    title: "2진수·16진수 변환",
    shortTitle: "진법",
    seoTitle: "2진수 16진수 변환기 | 진법 계산",
    ogDescription: "2진수와 16진수·10진을 서로 변환합니다. BigInt 지원.",
    description: "2진 문자열 또는 16진 문자열을 10진 및 상호 변환합니다.",
    introText: "저수준 학습·임베디드 디버깅 참고용입니다.",
    metaDescription: "2진 16진 10진 변환. 진법 계산, 모바일 즉시.",
    keywords: ["2진수", "16진수", "진법 변환", "바이너리"],
    bodyText: "매우 큰 수는 브라우저 한계가 있을 수 있습니다.",
    relatedIntro: "Unix 시간·UUID·Base64와 함께 보면 데이터 표현을 이해하기 쉽습니다.",
    relatedSlugs: ["unix-timestamp", "uuid-generator", "base64", "json-format"],
    toolSections: sec(
      "모드를 고른 뒤 숫자만 넣습니다.",
      "2진은 0과 1, 16진은 0-9A-F만 허용합니다.",
      "FF를 넣으면 10진과 2진으로 변환됩니다.",
      "부동소수는 이진 분수로 표현되어 복잡해질 수 있습니다.",
    ),
    faq: faq([
      { q: "음수는?", a: "부호 없는 정수 위주로 다룹니다." },
      { q: "앞에 0b를 붙이나요?", a: "이 도구는 숫자만 입력합니다." },
      { q: "너무 길면?", a: "브라우저가 느려질 수 있습니다." },
      { q: "실수 변환은?", a: "지원하지 않습니다." },
      { q: "비트 연산은?", a: "별도 언어를 쓰세요." },
      { q: "암호화인가요?", a: "아니요. 단순 진법 변환입니다." },
    ]),
  },
  {
    slug: "lorem-ipsum",
    categoryId: "text",
    title: "로렘 입숨 생성",
    shortTitle: "로렘",
    seoTitle: "로렘 입숨 생성기 | 더미 텍스트",
    ogDescription: "문단·문장 수를 정해 로렘 입숨 더미 텍스트를 만듭니다.",
    description: "디자인·레이아웃용 더미 문단을 생성합니다.",
    introText: "시안·와이어프레임에 채울 글자가 필요할 때 쓰는 도구입니다.",
    metaDescription: "로렘 입숨: 문단·문장 수 지정. 더미 텍스트, 모바일 즉시.",
    keywords: ["로렘 입숨", "더미 텍스트", "lorem ipsum", "레이아웃"],
    bodyText: "라틴어 더미이며 의미가 없습니다.",
    relatedIntro: "글자 수·줄바꿈 정리와 함께 쓰기 좋습니다.",
    relatedSlugs: ["char-count", "whitespace", "slugify", "json-format"],
    toolSections: sec(
      "문단 수와 문단당 문장 수를 선택합니다.",
      "같은 문장을 반복해 문단을 만듭니다.",
      "짧은 문단 여러 개로 카드 UI를 채울 수 있습니다.",
      "실제 콘텐츠를 대체하지 마세요.",
    ),
    faq: faq([
      { q: "한글은?", a: "이 도구는 라틴 로렘만 제공합니다." },
      { q: "저작권은?", a: "일반적으로 더미로 사용 가능하지만 서비스 정책을 확인하세요." },
      { q: "문장 수가 많으면?", a: "브라우저가 느려질 수 있습니다." },
      { q: "번역은?", a: "제공하지 않습니다." },
      { q: "SEO에 넣으면?", a: "검색 품질에 좋지 않을 수 있습니다." },
      { q: "PDF에도?", a: "복사해 붙이면 됩니다." },
    ]),
  },
  {
    slug: "slugify",
    categoryId: "text",
    title: "대소문자·슬러그 변환",
    shortTitle: "문자 변환",
    seoTitle: "대소문자 변환·슬러그 생성 | URL 문자열",
    ogDescription: "대문자·소문자·단어 첫 글자·슬러그로 바꿉니다. URL용은 슬러그 모드.",
    description: "영문 케이스를 바꾸거나 슬러그(URL 친화 문자열)를 만듭니다.",
    introText: "제목·코드 스타일을 맞추거나, permalink용 문자열이 필요할 때 씁니다.",
    metaDescription: "대소문자 변환·슬러그: UPPER, lower, Title, slug. 브라우저만, 복사 가능.",
    keywords: ["대소문자 변환", "슬러그", "URL 친화", "title case", "permalink"],
    bodyText: "슬러그 모드에서는 한글·한자가 제거되거나 빈 값이 될 수 있습니다. CMS 규칙을 따르세요.",
    relatedIntro: "HTML 이스케이프·URL 인코딩·공백 정리와 같은 편집 흐름에 넣기 좋습니다.",
    relatedSlugs: ["html-escape", "url-encode", "regex-tester", "whitespace", "char-count"],
    toolSections: sec(
      "모드를 고른 뒤 원문을 입력합니다. 슬러그는 실시간으로, 대소문자 모드도 바로 반영됩니다.",
      "슬러그: NFKD 정규화 후 라틴·숫자·하이픈 위주. 대소문자: 선택한 규칙에 따라 변환합니다.",
      "Hello World를 슬러그로 두면 hello-world에 가깝게, 대문자 모드면 HELLO WORLD 형태로 볼 수 있습니다.",
      "슬러그 고유성·중복 검사는 하지 않습니다.",
    ),
    faq: faq([
      { q: "한글 제목이 슬러그에서 사라져요.", a: "라틴 슬러그만 남기는 단순 규칙입니다. CMS 로마자 변환을 쓰세요." },
      { q: "Title case는 한글에도 되나요?", a: "라틴 단어 위주로 동작합니다. 한글 문맥은 수동으로 확인하세요." },
      { q: "언더스코어는?", a: "슬러그 모드에서는 하이픈으로 통일합니다." },
      { q: "중복 검사는?", a: "하지 않습니다." },
      { q: "대문자만 바꾸고 싶어요.", a: "‘모두 대문자’ 모드를 선택하세요." },
      { q: "SEO에 최적인가요?", a: "참고용이며, 실제 SEO는 콘텐츠를 따릅니다." },
    ]),
  },
  {
    slug: "random-picker",
    categoryId: "utility",
    title: "목록에서 하나 뽑기",
    shortTitle: "하나 뽑기",
    seoTitle: "랜덤 추첨 | 줄 단위로 하나 선택",
    ogDescription: "줄바꿈으로 구분한 목록에서 무작위로 한 줄을 뽑습니다.",
    description: "팀·메뉴·순서를 정할 때 쓰는 간단한 추첨입니다.",
    introText: "공정한 제비가 필요하면 별도 절차를 따르세요.",
    metaDescription: "목록 랜덤 추첨: 줄 단위. 회식·게임 참고, 모바일 즉시.",
    keywords: ["랜덤 추첨", "제비 뽑기", "하나 뽑기", "팀 나누기"],
    bodyText: "도박·복권 등 법이 정한 절차를 대체하지 않습니다.",
    relatedIntro: "난수·동전·퍼센트와 비슷한 맥락입니다.",
    relatedSlugs: ["random-number", "coin-flip", "percent", "password-generator"],
    toolSections: sec(
      "한 줄에 후보 하나씩 적고, 필요하면 ‘여러 명 뽑기’에서 인원 수를 고른 뒤 실행합니다. 순서를 섞을 때는 ‘목록 섞기’를 씁니다.",
      "빈 줄은 무시합니다. 여러 명 뽑기는 서로 다른 줄을 무작위로 고릅니다(후보가 부족하면 가능한 만큼만).",
      "점심 메뉴·발표 순서처럼 한 번에 하나 또는 여러 개를 뽑을 수 있습니다.",
      "공정 추첨·법적 제비는 별도 절차와 기록이 필요할 수 있습니다.",
    ),
    faq: faq([
      { q: "여러 명 한 번에 뽑으려면?", a: "‘여러 명 뽑기’에서 수량을 정하고 실행하세요. 후보가 부족하면 가능한 만큼만 나옵니다." },
      { q: "순서가 공정한가요?", a: "브라우저 난수에 의존합니다." },
      { q: "가중치는?", a: "지원하지 않습니다." },
      { q: "복붙이 안 돼요.", a: "줄바꿈 형식을 확인하세요." },
      { q: "같은 게 나왔어요.", a: "무작위라 가능합니다. 다시 뽑으세요." },
      { q: "법적 추첨은?", a: "공인 절차를 따르세요." },
    ]),
  },
  {
    slug: "coin-flip",
    categoryId: "utility",
    title: "동전 던지기",
    shortTitle: "동전",
    seoTitle: "동전 던지기 | 앞뒤 무작위",
    ogDescription: "앞면·뒷면을 무작위로 고릅니다. 저장 없이 브라우저만.",
    description: "동전 한 번의 결과를 시뮬레이션합니다.",
    introText: "가벼운 선택을 할 때 쓰는 도구입니다.",
    metaDescription: "동전 던지기: 앞뒤 랜덤. 모바일 즉시, 로그인 없음.",
    keywords: ["동전 던지기", "앞뒤", "랜덤 선택", "YES NO"],
    bodyText: "실제 동전이 아닙니다. 중요한 결정은 합의하세요.",
    relatedIntro: "난수·목록 뽑기·퍼센트와 비슷한 용도입니다.",
    relatedSlugs: ["random-picker", "random-number", "percent", "dday"],
    toolSections: sec(
      "버튼을 누르면 앞면 또는 뒷면이 나옵니다.",
      "0 또는 1에 무작위로 대응합니다.",
      "연속으로 여러 번 던질 수 있습니다.",
      "물리적 공정성은 보장하지 않습니다.",
    ),
    faq: faq([
      { q: "공정한가요?", a: "브라우저 난수를 씁니다." },
      { q: "동전이 없을 때?", a: "이 도구로 대체할 수 있습니다." },
      { q: "확률을 바꿀 수 있나요?", a: "50:50 고정입니다." },
      { q: "기록이 저장되나요?", a: "아니요." },
      { q: "스포츠 심판용?", a: "공식 경기는 규정을 따르세요." },
      { q: "애니메이션은?", a: "결과만 표시합니다." },
    ]),
  },
];
